# Generated by Django 3.2.19 on 2023-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetsu_app', '0006_auto_20230608_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='request_date',
            field=models.DateField(null=True),
        ),
    ]
